[env:m5stick-c-plus2]
platform = espressif32
board = m5stick-c-plus2
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5StickCPlus2@^1.0.0
build_flags =
    -DGHOST_M5STICK
    -DCORE_DEBUG_LEVEL=4
    -std=c++17
board_build.partitions = default_8MB.csv
